### ISSUE TITLE
Can't access any image from feed.

### ISSUE THREAD

**Issue by scottmcpherson** [danmactough/node-feedparser#101]
For some reason, I'm unable to access image's urls and titles. Everything else is loaded. When I console.log the  item.image.url I get undefined. Same thing with item.image.title.

``` javascript
       .on('readable', function () {
            // do something else, then do the next thing
            var stream = this, item;
            while (item = stream.read()) {
                console.log( 'Got article: %s', item.title || item.description );
                console.log( 'article link: ', item.link );
                console.log( 'article date: ', item.pubdate );
                console.log( 'article image url: ' + item.image.url ); // this is logging undefined
            }
        });

```

Any ideas? I've tried several RSS feeds with no luck.

**Comment by martinmurciego** [comment]
I could see that in the Mailtrain tool that uses this module: it includes the featured image along with the summary when I use a Wordpress plugin to include it in the RSS Feed.
`	<item>
		<title>El 18 de febrero se realizará la Jornada Internacional de Enfermería Familiar y Comunitaria</title>
		<link>https://salud.misiones.gob.ar/el-18-de-febrero-se-realizara-la-jornada-internacional-de-enfermeria-familiar-y-comunitaria/</link>
				<pubDate>Mon, 10 Feb 2020 16:44:22 +0000</pubDate>
		<dc:creator><![CDATA[Jonatan]]></dc:creator>
				<category><![CDATA[Noticias]]></category>

		<guid isPermaLink="false">https://salud.misiones.gob.ar/?p=15464</guid>
				<description><![CDATA[<img width="150" height="150" src="https://salud.misiones.gob.ar/wp-content/uploads/2020/02/jornadas-internacional-de-enfermeria-1-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" style="display: block; margin-bottom: 5px; clear:both;max-width: 100%;" link_thumbnail="" />El 18 de febrero, a partir de las 8 horas, se realizará la Jornada Internacional de Enfermería Familiar y Comunitaria en el salón auditorio de la Escuela de Enfermería de la UNaM. En este encuentro disertaran las Enfermeras Ana Romero García, Residente de Enfermería Familiar y Comunitaria de la Unidad Docente de Girona ICS- España. [&#8230;]]]></description>`
