### ISSUE TITLE
Getting multiple 'readable' events sometimes for a Google News feed

### ISSUE THREAD

**Issue by beaugunderson** [danmactough/node-feedparser#127]
Using [this URL](https://news.google.com/news/feeds?pz=1&cf=all&ned=us&hl=en&output=rss) and piping a `request` into a FeedParser instance I sometimes get a `readable` event for each story and sometimes one `readable` event that has all stories (the latter being how I believe it's supposed to work).

**Comment by sungwoncho** [comment]
> It's the core streams interface that determines how many times readable gets triggered.

I am fetching an rss feed with only 1 item, but multiple `readable` events are being fired. Is this an expected behavior?

**Comment by danmactough** [comment]
> Are you saying this is also an expected behavior?

Correct
