### ISSUE TITLE
Non-stream input

### ISSUE THREAD

**Issue by OliverJAsh** [danmactough/node-feedparser#129]
I have a string that I want to parse. Can I pass it through FeedParser without having to create a stream out of my string?

**Comment by danmactough** [comment]
@bitinn Did you figure this out?

In your first example, your `parser` input wasn't a stream, so you would have to manually signal it to end by calling `parser.end()`.

Similarly, in your second example, if `data.body` is a string, then you have to manually signal `parser`.  This might work:

```js
var log = fs.createWriteStream('log.txt');
var parser = new FeedParser();
parser.write(data.body).pipe(log);
parser.end();
```
