### ISSUE TITLE
Date time with UTC isn't parsed correctly

### ISSUE THREAD

**Issue by projectgheist** [danmactough/node-feedparser#133]
When the date time is defined in a feed post like:

Wed, d mmm 2015 23:56:01 -0500

It will then output it in the pubdate variable as:

Thu mmm dd 2015 04:14:02 GMT+0000 (GMT Standard Time)

Would it be possible to expose the original date string from the post?

**Comment by danmactough** [comment]
The original date is always there. Assuming each post can be referred to as `post`, it's `post['rss:pubdate']`. That will contain the string as presenting in the feed. Hope that helps.

**Comment by projectgheist** [comment]
Thank you very much that indeed solved my issue
