### ISSUE TITLE
Multiple elements of same type ignored in namespaces

### ISSUE THREAD

**Issue by scottgarner** [danmactough/node-feedparser#138]
I hope I'm describing this correctly. The feed I'm working with has a "metadata" namespace and elements that appear once make it through the parser and are still accessible:

```
<metadata:show>...</metadata:show>
```

...ends up in...

```
article["metadata:show"]['#']
```

Elements that appear more than once seem to not make it:

```
<metadata:formatLink></metadata:formatLink>
<metadata:formatLink></metadata:formatLink>
<metadata:formatLink></metadata:formatLink>
```
... seem to be inaccessible.

What am I missing?

**Comment by danmactough** [comment]
Do you have a link to the feed?

**Comment by scottgarner** [comment]
Thank you for the reply, Dan. Unfortunately it's a non-public feed. Let me double check and see if I can share a static version with you.

**Comment by danmactough** [comment]
You can email me at gmail.com

**Comment by scottgarner** [comment]
Perfect! I'll email you shortly.

**Comment by danmactough** [comment]
I think it's just that feedparser (well, the sax library, technically) lowercases all the element names, so you'll need to access it as `metadata:formatlink`.

**Comment by scottgarner** [comment]
Thanks for your help, @danmactough. It looks like everything is fine with feedparser, but that there is a problem with the feed and those fields are only present in the first 5 results. I'm pulling 35 in the production code, which is why I was so confused. In the static feed I sent to you, I only pulled 5 results, so the data was present.

Sorry for the wild goose chase and thanks again!

**Comment by danmactough** [comment]
haha cool
