### ISSUE TITLE
rss 2.0 feed not recognized

### ISSUE THREAD

**Issue by ktiniatros** [danmactough/node-feedparser#139]
Hi,

this feed: https://www.facebook.com/feeds/page.php?format=rss20&id=44015482829 is not recognized as a valid rss feed. Any ideas why?

Thanks!

PS: example: https://gist.github.com/ktiniatros/4ca5c1093cda2e8e99b7

**Comment by danmactough** [comment]
I think you probably need to handle a compressed response (notice the `Content-Encoding` header, below). See this example: https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js

```
⇰ http "https://www.facebook.com/feeds/page.php?format=rss20&id=44015482829"
HTTP/1.1 200 OK
Cache-Control: private, no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 15217
Content-Type: application/rss+xml
Date: Tue, 12 May 2015 05:30:06 GMT
Expires: Sat, 01 Jan 2000 00:00:00 GMT
Last-Modified: Mon, 11 May 2015 18:07:01 -0700
Pragma: no-cache
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-FB-Debug: TeraBmu6KsQRK54MAYMioaIGOcWJCKiepTz9Fdw0HKOEtfB9R7vEB8UiqBL14qYl5sDgL3rX9TfBYHYR/76EkA==
X-Frame-Options: DENY
```

**Comment by ktiniatros** [comment]
Actually it was not the compressed response but the missing user-agent.
Thanks to your response I found out that the header for the accepted browsers was missing. Thank you very much!

    req.setHeader('user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36');
