### ISSUE TITLE
End event is emoted even if error event has been emited

### ISSUE THREAD

**Issue by SamiSammour** [danmactough/node-feedparser#140]
I am having an issue when the 'error' event is emitted the 'end' event is emitted also so I get an error that the callback was already called.
I have fixed my code and it looks like this:
```javascript
feedparser.on('error', function(err) {
  hasError = true;
  done(err);
});
feedparser.on('end', function() {
  if (!hasError)
    done(null, items);
});
```
But I think it is a bug here and need to be fixed.

**Comment by danmactough** [comment]
I feel you. The problem is that in this context, you can have more than one error emitted, and not every event is fatal. The only way to know you're done is the end event. Does that make sense?

**Comment by SamiSammour** [comment]
Well I think if an error is not fatal then it can be emitted over an event other than the error event.

**Comment by danmactough** [comment]
> if an error is not fatal then it can be emitted over an event other than the error event

I don't understand.
