### ISSUE TITLE
Soundcloud's new podcast feeds 

### ISSUE THREAD

**Issue by jcbator** [danmactough/node-feedparser#141]
Just wondering which tag takes precedence for the "author" piece of the metadata.

For this feed: http://feeds.hearstartup.com/hearstartup - the author says "Soundcloud Feeds" instead of the expected "Gimlet".

"Gimlet" is placed in the "iTunes:author" tag, and "Soundcloud Feeds" appears in the "webMaster" tag.

Is it possible to default (for lack of a better word) to the iTunes tags if you have that particular purpose?

Thanks a lot!

**Comment by danmactough** [comment]
> Is it possible to default (for lack of a better word) to the iTunes tags if you have that particular purpose?

The `author` tag gives precedence to the elements defined in the specs: https://github.com/danmactough/node-feedparser/blob/master/main.js#L499-L516 And only back-fills with alternatives: https://github.com/danmactough/node-feedparser/blob/master/main.js#L674-L679

If you have a podcast app, then it probably makes sense for you to have app logic that gives precedence to the `itunes:author` property, if present. But feedparser wouldn't do that for you.

Hope that answers your question.

**Comment by jcbator** [comment]
Perfect - makes sense!
