### ISSUE TITLE
Channel link is replaced by alternate links

### ISSUE THREAD

**Issue by EggiJan** [danmactough/node-feedparser#142]
I've found a feed, where the channel link is replaced by the atom alternate links.

The feed: http://feeds.feedburner.com/mobile-macs-enhanced-podcast

Expected: meta.link = "http://freakshow.fm"
Result: meta.link = "http://freakshow.fm/feed/opus/"

I would suggest using the channel link and use the alternate links as fallback.

**Comment by danmactough** [comment]
Thanks for the report @EggiJan.  Fixed via 40707d6 and published as v1.1.0.
