### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by BrandonMathis** [danmactough/node-feedparser#147]
I'm getting a CORS error when I try to pull data from an rss feed.

I'm using browserify. Is that not supported?

```
Errors XMLHttpRequest cannot load example.com/rss/feed/url No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
```

**Comment by danmactough** [comment]
feedparser doesn't do any http fetching. it just ingests a stream of data. no idea if it can be browserified. however you're fetching the data is where you need to pursue this error.
