### ISSUE TITLE
Forbes feed doesn't work?

### ISSUE THREAD

**Issue by voidale** [danmactough/node-feedparser#149]
`http://www.forbes.com/real-time/feed2/` when I try to parse this feed it will output the following error: 
`{ [Error: Not a feed] stack: [Getter] }`

Visiting the link seems like a valid RSS link + works on other website to parse it.

**Comment by danmactough** [comment]
@voidale Can you please post your code or relevant part of it? I am able to parse that feed just fine.

One likely suspect is that you're piping the http response directly to feedparser when the response is actually gzipped -- for example.

**Comment by voidale** [comment]
@danmactough yeah I think you're right how can I overcome this? I didn't expect it thanks!
here is my code:
http://pastebin.com/PkcMsH0q

**Comment by danmactough** [comment]
Check out the examples directory

**Comment by voidale** [comment]
@danmactough awesome thanks sorry I missed this one, Didn't know it's important

**Comment by voidale** [comment]
just a small update it seems to work and there is no zlib, I fetched the url without www. and forbes doesn't allow that.. there is no RSS without www. >.<
