### ISSUE TITLE
Not able to get script tag from Rss Link

### ISSUE THREAD

**Issue by sharath1989** [danmactough/node-feedparser#151]
I am trying to pass http://www.deccanherald.com/mrss/videos.rss and able to get link, description, pubdate, description, author, categories.

But when I check the rss link in fiddler or postman I should get the script tag but not able to get the value from it. How can I get the value of script tag.

**Comment by danmactough** [comment]
"script" is not a [valid rss element](http://cyber.law.harvard.edu/rss/rss.html), so it's not one of the elements you'll see without a namespace prefix. You'll still see it as "rss:script" however. 

![image](https://cloud.githubusercontent.com/assets/357481/10403467/ccd6f6b2-6e99-11e5-9695-60d5b5bae462.png)

**Comment by sharath1989** [comment]
thanks for the reply,  but can't I get the value of the script tag and moreover the value is there but it doesn't show up when parsed
