### ISSUE TITLE
About the 'end' event

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [danmactough/node-feedparser#154]
I need to know a few things about the 'end' event, they're all rather short questions:

 - Is it always emitted when feedparser is done with the stream?
 - Is it always the last event to be emitted?
 - Is it only emitted once?
 - What does it pass to the listener?

Thanks.

**Comment by danmactough** [comment]
`end` event doesn't pass anything. I think the streams api docs answer your other questions: https://github.com/nodejs/readable-stream/blob/master/doc/stream.markdown#event-end

**Comment by MySidesTheyAreGone** [comment]
Thanks!
