### ISSUE TITLE
"Not a feed" for something that looks valid

### ISSUE THREAD

**Issue by crrobinson14** [danmactough/node-feedparser#155]
Hey folks, I'm trying to process http://rssfeeds.usatoday.com/usatoday-NewsTopStories with this tool and it's throwing a "Not a feed" error. This is being processed fine by other feed processors such as https://pypi.python.org/pypi/feedparser and it looks visually OK. It's missing the open XML tag but I tried dumping it to an XML file and putting that in there as a test and that doesn't resolve the error. Appreciate any advice.

**Comment by danmactough** [comment]
@crrobinson14 The feed is probably being served with gzip compression. Take a look at this example for how to make sure you're sending plain text to feedparser: https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js

**Comment by crrobinson14** [comment]
Thanks, @danmactough. It wasn't gzip'd but that tip helped me sort it out by hooking in at the spot where you did the example above. When I looked at the raw data there it turned out the site is sending back an alternate response based on user-agent and other headers. Different problem but similar solution. Thanks!

**Comment by danmactough** [comment]
Glad you figured it out.
