### ISSUE TITLE
'end' event?

### ISSUE THREAD

**Issue by dandart** [danmactough/node-feedparser#163]
Hi

Is it possible to emit an 'end' event, or better, support promises? I'd like to know when the stream has ended so I can resolve a promise and pass the finished data.

Cheers

**Comment by mooyoul** [comment]
Yup you can.
feedparser emits `end` event.
I'm using this event to resolve my own Promise method.

[See `fetch` function on this example](https://github.com/danmactough/node-feedparser/issues/166#issuecomment-206215547)

**Comment by dandart** [comment]
Lovely, thanks!
