### ISSUE TITLE
onFinished Method?

### ISSUE THREAD

**Issue by AbdelHamidAhmed** [danmactough/node-feedparser#167]
Is there an onFinished method when the feedparser is done reading all the data from the stream?

**Comment by danmactough** [comment]
I think the [`end` event](https://nodejs.org/dist/latest-v4.x/docs/api/stream.html#stream_event_end) is what you're looking for.

**Comment by AbdelHamidAhmed** [comment]
What I mean it is, I wanted to pass all the data to a certain object AFTER the parser has done all the loading, because when I'm using multiple rss feeds, it takes some time to load, and I have to refresh the page with the data a few times until the parser gets all the data. So what I am trying to accomplish is wait until all the data is loaded and then passing it to the object, if it's possible

**Comment by mooyoul** [comment]
Why don't you use [`end` event which used in previous comment](https://github.com/danmactough/node-feedparser/issues/166#issuecomment-206215547)?

**Comment by AbdelHamidAhmed** [comment]
I figured it out, thanks a lot :)
