### ISSUE TITLE
TypeError: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by dvdgrdll** [danmactough/node-feedparser#177]
I'm getting this error when trying to parse YouTube RSS, like this one:
https://www.youtube.com/feeds/videos.xml?channel_id=UCi8e0iOVk1fEOogdfu4YgfA

Impossible to track where it is coming from.

**Comment by danmactough** [comment]
@dvdgrdll This kind of error could be caused by not decompressing a compressed request response. See this [example](https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js).

Please be sure to include the full error and stack trace and your code if you need more help.
