### ISSUE TITLE
Error Cannot read property '#' of undefined while add specific rss link

### ISSUE THREAD

**Issue by sintret** [danmactough/node-feedparser#182]
12:46]  
Error in feed parser module http://www.tabloidbintang.com/feeds/rss/all  and  error result: TypeError: Cannot read property '1' of null

[12:46]  
Error in feed parser module http://www.beritasatu.com/rss/beritasatu.xml  and  error result: TypeError: Cannot read property '#' of undefined

**Comment by danmactough** [comment]
Hi, @sintret. Those errors without stack traces and the code that goes with them don't tell me much. Neither of those feeds causes any errors for me.
