### ISSUE TITLE
Error: "Not a feed"

### ISSUE THREAD

**Issue by arjanfrans** [danmactough/node-feedparser#184]
I have an RSS feed that seems to be valid:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds2.feedburner.com%2FTheSwissRamble

But the feed parser emits the "Not a feed" error. Is there something wrong with this RSS feed?

**Comment by danmactough** [comment]
I can parse that feed just fine. Make sure you're not trying to parse a compressed or gzipped response: https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js
