### ISSUE TITLE
How do I know if a feed is parsed successfully?

### ISSUE THREAD

**Issue by aniskhan001** [danmactough/node-feedparser#185]
Currently, I can get to know that if a feed is parsed by the `readable()` method. But that loops multiple time (total article count on that feed). I want to know that with a single method. Is that possible?

**Comment by oazya500** [comment]
there is 

feedparser.on('end', function(error) {
  
  });

but is it work fine . me to want to parse all feed then insert items to DB to decrease the cost to insertion time

**Comment by zeeshanjan82** [comment]
end event is not working fine. It is fired before.

**Comment by danmactough** [comment]
Here's a [great demo](https://github.com/scripting/feedParserDemo) if you're still looking for guidance.
