### ISSUE TITLE
Cannot be used on the React Native

### ISSUE THREAD

**Issue by dengyhgit** [danmactough/node-feedparser#191]
<img width="512" alt="default" src="https://cloud.githubusercontent.com/assets/10509682/21854302/324b45fe-d855-11e6-9c10-342a4bfb7325.png">

**Comment by dengyhgit** [comment]
why?

**Comment by danmactough** [comment]
@dengyhgit I can't tell what you are asking for, and you posted a picture of a system icon or something. If this is a bug report, you will need to describe the bug. If it's a feature request, PRs are welcome.
