### ISSUE TITLE
What events should fire off for a bad feed?

### ISSUE THREAD

**Issue by cdellinger** [danmactough/node-feedparser#194]
This is related to issue #186 (https://github.com/danmactough/node-feedparser/issues/186).  It got closed and wasn't sure if anyone was still seeing comments there, sorry if I'm creating more noise by creating this issue, I'm never sure how to handle closed issues in GitHub if questions still remain.  

My question is what the behavior should be with the new 2.0.0 version.  If I understood your response in #186, if a feed that is badly formed is processed, we should see an `error `event emitted and we should not see an `end `event emitted, is that correct?

My question/issue is I see that behavior happening unless there is logic in the `readable `event.  If code resides in the `readable `event, I see both an `error `and `end `event firing off. Is that behavior expected? Should the `error `event record that some error occurred and the `readable` event check against this value and not process if that was the case?

**Comment by danmactough** [comment]
@cdellinger I'm sorry you're feeling confused. I don't have any more guidance or ideas than what I said in #186.

If you can identify a bug, please open a new issue. But there's really nothing I can do here, so I'm going to close this issue.
