### ISSUE TITLE
Max Listener Problems

### ISSUE THREAD

**Issue by Ryu945** [danmactough/node-feedparser#196]
When implementing the code like the examples shown; I get an issue with max listeners.  I can set the listener count higher to suppress the warning but this still makes the nodejs code unstable and crash some times.  I also see error messages about socket hang.

This may be something with the request module so perhaps an example of how to use this module without request would help.

**Comment by danmactough** [comment]
Max listener warnings don't have anything to do with feedparser.

If you think you have a helpful PR to explain an alternative way to use feedparser, I'd be happy to consider a PR! 😄
