### ISSUE TITLE
Parsing time increases after first use on an interval

### ISSUE THREAD

**Issue by gintil** [danmactough/node-feedparser#199]
I noticed that when parsing numerous feeds on an interval, the first time it runs it's always the fastest but afterwards it slows down. I tried parsing around ~200 links and on the first interval it managed to do it all in around 25-30 seconds, however after that first interval and in subsequent intervals, the time taken increased until it stabilized at around 50-60 seconds and no longer increases - is this normal? 

I have tested this without the feedparser and just requesting the links, and it took around 15-25 seconds and was stable in that area. The method for feedparsing is pretty much the same as the one on the readme, except repeated for however many links.

**Comment by danmactough** [comment]
That is not expected behavior and not something I've heard before.

If you have code that can reproduce the condition, maybe we can see if there's a bug. Short of that, there's really nothing I can do, so I'm going to close this.
