### ISSUE TITLE
[Question] How to get only one latest feed item?

### ISSUE THREAD

**Issue by iamfrntdv** [danmactough/node-feedparser#200]
Hi! I'm new to JS, could someone help how to get only one latest feed item?

Thank you.

**Comment by r1b** [comment]
I would like this feature as well - right now I implement this with an external LRU cache.

**Comment by danmactough** [comment]
Due to the nature of feeds, you have no guarantee that any particular item (such as the first or last item) is the "latest" or most recent. You'll have to examine each item and choose the one you want.
