### ISSUE TITLE
Transform pipe to stdout

### ISSUE THREAD

**Issue by jonathan-chin** [danmactough/node-feedparser#204]
hey,

pardon my ignorance; I don't have much experience writing or coding with NodeJS streams. I want to use feedparser to pull a particular field from an rss feed (the uid the site generates for each article) and pipe that to another process. how can I do that?

I've tried using stream.emit and stream.write but I keep getting
```TypeError: Invalid data, chunk must be a string or buffer, not object```

**Comment by danmactough** [comment]
Hi, @jonathan-chin. Here's a [great demo](https://github.com/scripting/feedParserDemo) that should help you get started if you're still struggling.

**Comment by bitwombat** [comment]
The demo doesn't do what OP wants. It uses a callback to send all the accumulated data.

What OP (and I) am trying to do is something like:

```
fs.createReadStream(__dirname + '/rss.xml').pipe(feedParser).pipe(process.stdout)                               ```
Because feedparser is a transform stream, I keep thinking this is possible, but stream.write in 'readable' isn't doing the trick...
