### ISSUE TITLE
Usage Example does not work

### ISSUE THREAD

**Issue by Cagrosso** [danmactough/node-feedparser#213]
Copying and running the usage example on a RSS feed throws:

`stream.pipe is not a function`

This seems to be corrected by changing:

`stream.pipe(feedparser);`

to:

`response.pipe(feedparser)`

Is there a specific reason as to why the stream variable is used instead of response?  Am I leaving something out that causes the original code to error?

**Comment by danmactough** [comment]
@Cagrosso I think you didn't copy it correctly, but you'll need to paste your code. The usage example works. 😉
