### ISSUE TITLE
Parsing XML attributes

### ISSUE THREAD

**Issue by Ziker22** [danmactough/node-feedparser#214]
Hi,
Is there a way to get custom xml attributes when promise is resolved ?
example
```
<item segment="home">
<title>blah</title>
<link>
blabla.com
</link>
</item>
```

I want to parse segment="home" part

thx in advance

**Comment by danmactough** [comment]
Hey, @Ziker22. That's an _extremely_ non-standard thing to see. But the good news you can do it!

As you are parsing, each item will have lots of extra properties. If we assume an item is named `item`, then you'll see that `item['rss:@']` (if it's an rss feed) or `item['atom:@']` (if it's an atom feed) will be an object of name/value pairs for any attributes of the item. So in your example:

```js
console.log(item['rss:@']['segment']);
// prints "home"
```
Hope that helps.

**Comment by clakech** [comment]
Thanks @danmactough, this answer helps me ;)

**Comment by clakech** [comment]
@danmactough what if my item's properties have extra attributes like:

```
<item segment="home">
<title anotherAttribute="hello">blah</title>
<link>
blabla.com
</link>
</item>
```
Any chance to get the anotherAttribute value 'hello' on item.title ?

**Comment by danmactough** [comment]
@clakech yup. same thing: item.title['rss:@']['anotherAttribute']
