### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by luizfduartejr** [danmactough/node-feedparser#221]
Here in Brazil many feeds use ISO-8859-1 instead UTF-8 encoding. How can I handle this using your module?

**Comment by Sigmus** [comment]
The example provided in this repo uses the request library for HTTP data fetching. Look for ```encoding``` [here](https://github.com/request/request#requestoptions-callback]).

**Comment by luizfduartejr** [comment]
Yeah, I realized that later. Sorry for my dumbness.

**Comment by Sigmus** [comment]
There are no dumb questions!
