### ISSUE TITLE
callback on feedparser.on('readble')

### ISSUE THREAD

**Issue by aliir74** [danmactough/node-feedparser#228]
Hi. I want pass a array after all readable feed content catch. How can I call a callback at the end of feed parsing?

**Comment by danmactough** [comment]
Hi, @aliir74. Here's a [great demo](https://github.com/scripting/feedParserDemo) app that should help you out: https://github.com/scripting/feedParserDemo

**Comment by aliir74** [comment]
Thanks @danmactough
