### ISSUE TITLE
Not a Feed Error

### ISSUE THREAD

**Issue by jaseemkp** [danmactough/node-feedparser#232]
Getting parse error on http://www.thenewsminute.com/andhra.xml and http://www.indiaglitz.com/home_1.xml

**Comment by ScionOfBytes** [comment]
@jaseemkp Can you elaborate on the exact error? Maybe share the error message?

If you check: https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fwww.indiaglitz.com%2Fhome_1.xml you'll see the second feed is, in fact, not valid.

**Comment by danmactough** [comment]
@jaseemkp It looks like you need to uncompress or un-gzip http://www.thenewsminute.com/andhra.xml before you pass it to feedparser. You should be able to adapt the [example](https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js).

As @ScionOfBytes noted (thanks!), http://www.indiaglitz.com/home_1.xml is not a valid feed.
