### ISSUE TITLE
Atom feed with relative URLs

### ISSUE THREAD

**Issue by scripting** [danmactough/node-feedparser#237]
I'm not enough of an expert in Atom to know if relative URLs are permissible but here's one that has them. 

http://xmlviewer.scripting.com/?url=http://talkingpointsmemo.com/account/feed/all/LpNewCzTqYYiHqtKqyTw5DaF1aUucgyyXb2dsqKU2yMr

(I wanted to run it through feedvalidator.org, but it appears to be down.)

Not sure what the right answer is. If you feel that TPM should change the feed I will bring the problem to them.

Dave

**Comment by danmactough** [comment]
Relative URLs are kosher (albeit annoying and foolish). Feedparser is supposed to turn relative URLs into absolute URLs. If it's not working on that feed, it's a bug.

**Comment by scripting** [comment]
Okay, it's a bug! ;-)

Unless something really weird is happening, which is always a possibility. 

It's evident in the river on my blog --

http://scripting.com/river.html

At this moment, the second item in the river comes from TPM. When I click the link it takes me to a page on scripting.com, because (presumably) an uncorrected relative URL passing up from feedparser. 

![image](https://user-images.githubusercontent.com/1686843/32454074-1b15cbc0-c2ec-11e7-94f8-e8cac7f32b8a.png)

**Comment by danmactough** [comment]
@scripting I'm seeing correct canonical URLs when I parse that feed. What version of feedparser are you using? (Maybe there _was_ a bug and it's now fixed.)

**Comment by scripting** [comment]
@danmactough --

It looks like the version is 2.2.1.

I did an npm update and now the version is 2.2.3.

So I was indeed running an old version.

I'll relaunch and see if items from that feed have correct URLs.

Sorry for not checking this first.

**Comment by scripting** [comment]
After installing the new version, we're still getting the bad links. 

![image](https://user-images.githubusercontent.com/1686843/32554621-6b22e936-c468-11e7-9306-78d1c12261df.png)

It's totally possible this is a bug in my software, that I'm looking at the wrong item in the object that's being returned, for example. 

As far as I know it's only this feed. I can put a workaround in the River browser for it, and am willing to. So I'm going to close this issue for now.

**Comment by danmactough** [comment]
@scripting I was wrong. It wasn't resolving the correct canonical URL _for the first item_. 😱

**Comment by danmactough** [comment]
Fix published as v2.2.4
