### ISSUE TITLE
item.link depends on the order in atom:link array

### ISSUE THREAD

**Issue by Alex7Kom** [danmactough/node-feedparser#244]
Items from Blogger feeds like [this one](http://www.itchyfeetcomic.com/feeds/posts/default) have an array of `<link>` elements:

```xml
<link rel='replies' type='application/atom+xml' href='http://www.itchyfeetcomic.com/feeds/7118724017542646224/comments/default' title='Post Comments' />
<link rel='replies' type='text/html' href='http://www.itchyfeetcomic.com/2017/11/worth-it.html#comment-form' title='6 Comments' />
<link rel='edit' type='application/atom+xml' href='http://www.blogger.com/feeds/6238329353013891803/posts/default/7118724017542646224' />
<link rel='self' type='application/atom+xml' href='http://www.blogger.com/feeds/6238329353013891803/posts/default/7118724017542646224' />
<link rel='alternate' type='text/html' href='http://www.itchyfeetcomic.com/2017/11/worth-it.html' title='Worth It' />
```

from which Feedparser currently chooses `<link rel='self'>` as item.link. If `<link rel='alternate'>` appears earlier than `<link rel='self'>` then `<link rel='alternate'>` is chosen.

This behavior was introduced in #234.

I'd like to see `<link rel='alternate'>` as `item.link` in this case but I'm not sure what is intended behavior.

**Comment by danmactough** [comment]
> I'd like to see <link rel='alternate'> as item.link in this case but I'm not sure what is intended behavior.

I think you're correct that `<link rel='alternate'>`, if present, should always be `item.link`.
