### ISSUE TITLE
Some feeds not parsing

### ISSUE THREAD

**Issue by mzontak** [danmactough/node-feedparser#258]
No output or error for the following feeds:

1. https://bridgewoodchurch.com/podcast?format=RSS
2. https://www.westgatechurch.org/westgate-teaching?format=rss

**Comment by mzontak** [comment]
Tested on node 6 and 8, with latest version of parser. Compressed example didn't work for the listed feeds.

**Comment by danmactough** [comment]
@mzontak I'm not seeing any problems. It's likely that the data you're sending to feedparser is not a feed. Can you post your code?

**Comment by mzontak** [comment]
Turns out that the parser was emitting an error, which made me think that processing stopped. Ignoring this error, the parser continues to parse and reaches the onreadable. Thanks.
