### ISSUE TITLE
Possible to use in windows environment?

### ISSUE THREAD

**Issue by GintokiHub** [danmactough/node-feedparser#260]
Hi, on windows is it possible to run this app? Through docker or Virtual Env.
Or perhaps some other way (chocalaty?).

Thank you!

- [ ] Review the [compressed example](https://github.com/danmactough/node-feedparser/blob/master/examples/compressed.js).
Can't find the answer I am searching for over there.

- [ ] Include which version of FeedParser you're using.
Non atm.

- [ ] Include which version of Node you're using.
x
- [ ] Include a link to any feed you're having a problem with.
x

**Comment by danmactough** [comment]
@GintokiHub This is not a complete application. It's just a library. It can be used in a Windows environment.
