### ISSUE TITLE
<link type="application/rss+xml"> was not parsed

### ISSUE THREAD

**Issue by slavaGanzin** [danmactough/node-feedparser#272]
Hello, thanks for your project.

I found that feedparser return empty feedUrls if I run:
```js
var rssFinder = require('rss-finder');
 
rssFinder('https://outsideonline.com').then(function(res) {
    console.log(res);
}).catch(function(err) {
    console.log(err);
});
```

Result:
```js
{ site: 
   { title: 'Pinterest Icon',
     favicon: 'https://www.outsideonline.com/sites/default/files/favicon_1.ico',
     url: 'https://www.outsideonline.com' },
  feedUrls: [] }
```

But this page has valid rss feed link in head section:
```html
<link rel="alternate" type="application/rss+xml" title="Semi-Rad" href="https://www.outsideonline.com/taxonomy/term/10311/%2A/feed">
```

Can you guide me through this issue?

**feedparser** 2.2.9
**node:** v9.4.0

**Comment by danmactough** [comment]
@slavaGanzin I think you should open an issue with rss-finder. This seems like something for them to debug -- feedparser isn't used to populate that `feedUrls` array.

**Comment by slavaGanzin** [comment]
@danmactough Sorry. My fault: mistook open windows :)

**Comment by danmactough** [comment]
No worries at all @slavaGanzin. Take in easy!
