### ISSUE TITLE
Unhandled incorrect header/body check

### ISSUE THREAD

**Issue by synzen** [danmactough/node-feedparser#277]
Here I used node-fetch to with `Accept-Encoding: gzip,deflate` (the default) for a feed that sends a erroneously sends back a response with `content-encoding: gzip` when the body is not actually compressed. Unfortunately it seems that feedparser doesn't detect such a problem here. node-fetch doesn't throw any errors for this unless you call `res.text()`, `res.json()` (see https://github.com/bitinn/node-fetch/issues/45), and instead I immediately pipe it to feedparser rather than letting node-fetch handle it

In my example below feedparser doesn't emit error and doesn't emit end.

feedparser v2.2.9
Node v12.7.0

Feed: https://eliteesp.es/category/galnet/feed/

```js
const FeedParser = require('feedparser')
const fetch = require('node-fetch')
const feedparser = new FeedParser()

fetch('https://eliteesp.es/category/galnet/feed/').then(res => {
  if (res.status !== 200) throw new Error('Non-200 status code')
  res.body.pipe(feedparser)
})

feedparser.on('error', function (error) {
  console.log('fp err', error)
  // always handle errors
});

feedparser.on('readable', function () {
  // This is where the action is!
  var stream = this; // `this` is `feedparser`, which is a stream
  var meta = this.meta; // **NOTE** the "meta" is always available in the context of the feedparser instance
  var item;

  while (item = stream.read()) {
    console.log(item);
  }
})

feedparser.on('end', function () {
  console.log('end')
})
```

There is no output when running this. Not sure if feedparser is supposed to handle this case though

**Comment by rdbcci** [comment]
Not sure what your asking, but if fetch returns encoded (gzip) you need to decode it before piping to feedparser. When I do this, this feed parses just fine.

**Comment by synzen** [comment]
`node-fetch` doesn't auto-decode the body unless prompted by the user (which is why it's lightweight and faster from my own tests - like the browser's fetch API) - instead, I let feedparser take on the body. This works over 99.999% of the time until I encountered this issue, where feedparser failed to detect an invalid feed for a feed like this (had me scratching me head for days as to what was happening).

You can see the link above has invalid content-encoding headers when you open it in chrome and you see `ERR_CONTENT_DECODING_FAILED`

![image](https://user-images.githubusercontent.com/18688793/62148787-650c0280-b2c8-11e9-9689-9cc516b2c1c5.png)


and the explanation for it: https://stackoverflow.com/questions/14039804/error-330-neterr-content-decoding-failed. TLDR; response says its gzipped, and it's actually not - browser is confused. I assume feedparser is confused here as well, but instead feedparser just hangs indefinitely

**Comment by rdbcci** [comment]
Not a node-fetch user, but parses fine as a mikeal request (feed header in this case indicates that is not encoded).

**Comment by synzen** [comment]
I get that `request` works, as you've said before, but I'm saying the problem is that feedparser isn't emitting any errors here, as I mentioned in my last sentence

**Comment by rdbcci** [comment]
Yea, just catching up to subtlety of your problem.

**Comment by rdbcci** [comment]
I just set myself up to use node-fetch. When I run it your feed with {compress:false} option, it works.

**Comment by synzen** [comment]
Yes it will work in that case because then their server will send an uncompressed body, with no gzip in `content-encoding` (the main problem with their feed)

but the point here is that feedparser is not emitting an error here when I really think it should - the issue is basically being swallowed up by the parser. I'm not trying to find a way to work with the feed, just trying to suggest that feedparser should emit an error so

1. Someone else doesn't spend hours scratching their heads why a feed may never resolve through feedparser
2. To handle it appropriately in error handling

**Comment by rdbcci** [comment]
I think Feedparser is just waiting for input. I think node-fetch maybe hung, not handling the decoding correctly in your offending feeds case. If that's the case  Feedparser may not be the place for the fix.

**Comment by danmactough** [comment]
@synzen This doesn't appear to be related to feedparser.

Make the following change to your example script:

```diff
- res.body.pipe(feedparser)
+ res.body.pipe(process.stdout)
```

You'll still see the pathological behavior -- no output, no errors. 🤷‍♂
