### ISSUE TITLE
Update examples to use something other than request

### ISSUE THREAD

**Issue by danmactough** [danmactough/node-feedparser#280]
See: https://dev.to/glitch/dev-diary-week-2-reading-a-feed-4mno#what-did-i-have-trouble-with

**Comment by scripting** [comment]
I've been reading up on this -- they say request is deprecated, but it doesn't seem that's actually what's going on. They decided they wanted to use the new callback functionality of async and promises, and realized if they tried to make that happen to request it would no longer be request. But there's no plan to take it out of the distribution. It would be insane, everything would break.

**Comment by danmactough** [comment]
As you say, there's no way to take `request` out of distribution. But I think the examples would be more helpful if they used one of the more modern http client libraries, which I think are more familiar to people now.

Also, all of the more modern alternatives simplify usage because they seamlessly handle compressed http responses. This is a pretty big win to me because even though I have an example of how to handle compressed feeds that I point to in the README -- practically begging people to review that example -- compressed feeds have led to quite a few bug reports that are actually user error. If users use one of the more modern http clients, they will never encounter those errors.

This is what I'm planning to use in place of my exiting examples: https://github.com/danmactough/node-feedparser/pull/281/files#diff-4ce2a74e765f3fd80601834eaaf9c8ca
