### ISSUE TITLE
react-native: Unable to resolve module `util` 

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [danmactough/node-feedparser#285]
![image](https://user-images.githubusercontent.com/64393724/103170152-1972d500-487d-11eb-8fda-0f7cc06f1638.png)

error message:

```
"Unable to resolve module `util` from `node_modules\\feedparser\\lib\\feedparser\\index.js`: util could not be found within the project.
```

**Comment by danmactough** [comment]
This library is written for node. If you want to use it with react-native, you'll need to figure out how to make node core modules (like `util`) available, but that's outside the scope of this project. Maybe this link will help: https://hackernoon.com/using-core-node-js-modules-in-react-native-apps-64acd4d07140
