### ISSUE TITLE
parseString API missing in latest version?

### ISSUE THREAD

**Issue by kenyee** [danmactough/node-feedparser#76]
I was using the parseString API in a previous version and it appears this is now missing in the latest version? :-P

Is it possible to add it back?  I can't find it in the code anywhere.

My use case is:
do http.get to read rss feed
if I get authorization error, re-auth
if not, take string and use parseString

so I need more control over the initial fetch of the data and don't want to use the feedurl technique that the latest API uses.

p.s., it's bad form to break old APIs ;-)

**Comment by polomoshnov** [comment]
What a pity! I also need parsing strings instead of urls.
