### ISSUE TITLE
long polling and new items

### ISSUE THREAD

**Issue by ralyodio** [danmactough/node-feedparser#91]
Is it possible to setup a long polling pattern that will only emit the newer items from the feed since the last time the parser was ran?

I can save the last  item.guid but not sure how I would know if stream items on the next interval were before or after the last item seen in the previous interval.

**Comment by yPhil-gh** [comment]
Dan, sorry if I seem to beat a long dead horse, but, what if you store the last item.link, then pass it to feedParser, and then stop the stream when you see item.link again?

Something like this:

```
          while ((item = stream.read())) {

            if (item !== null) {
              i++;

              if (typeof newLastItem === 'undefined') {
                newLastItem = item.link;
              }

              if (item.link !== lastItem && i < maxItems) {
                console.error('### PUSH i:[%s], This item:[%s], lastItem:[%s], newLastItem:[%s]', i, item.link, lastItem, newLastItem);

                feedItems.push(item);
              } else {
                console.error('### STOP i:[%s], This item:[%s], lastItem:[%s], newLastItem:[%s]', i, item.link, lastItem, newLastItem);
                this.close();
              }
            }
          }
```

It works, the only problem it that the items are sometimes in the wrong order... Am I missing something?
When you say "You have no control over the order of items in the feed" well, you pretty much know that they are in chronological order... right?

**Comment by danmactough** [comment]
> When you say "You have no control over the order of items in the feed" well, you pretty much know that they are in chronological order... right?

@yPhil-gh You don't know that, unfortunately. It's just a convention. It's valid to serve items in any order, and I've seen it happen.
