### ISSUE TITLE
How deal with encoding charset?

### ISSUE THREAD

**Issue by ebuildy** [danmactough/node-feedparser#96]
I try to parse the RSS http://fr.canoe.ca/rss/feed/nouvelles/aujourdhui.xml encoded in ISO-8859-1 charset.

I use iconv piped to encode the XML to UTF8 but how can I get the RSS encoding before apply the parsing?

Here the code I am using: https://gist.github.com/ebuildy/0b5023e2d97ebc2e4a57

Thanks

**Comment by AdanTL** [comment]
@danmactough can you put @szwacz 's solution? I got the same problem but his page is not available.

**Comment by szwacz** [comment]
@AdanTL File in my repo still exists, just have been moved: https://github.com/szwacz/sputnik/blob/master/app/core/helpers/feed_parser.js#L42
